# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/quinn/graphicspipeline

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/quinn/graphicspipeline

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quinn/graphicspipeline/CMakeFiles /home/quinn/graphicspipeline/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/quinn/graphicspipeline/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named physicspipeline

# Build rule for target.
physicspipeline: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 physicspipeline
.PHONY : physicspipeline

# fast build rule for target.
physicspipeline/fast:
	$(MAKE) -f CMakeFiles/physicspipeline.dir/build.make CMakeFiles/physicspipeline.dir/build
.PHONY : physicspipeline/fast

#=============================================================================
# Target rules for targets named state

# Build rule for target.
state: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 state
.PHONY : state

# fast build rule for target.
state/fast:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/build
.PHONY : state/fast

#=============================================================================
# Target rules for targets named graphicspipe

# Build rule for target.
graphicspipe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphicspipe
.PHONY : graphicspipe

# fast build rule for target.
graphicspipe/fast:
	$(MAKE) -f CMakeFiles/graphicspipe.dir/build.make CMakeFiles/graphicspipe.dir/build
.PHONY : graphicspipe/fast

#=============================================================================
# Target rules for targets named graphicspipeline

# Build rule for target.
graphicspipeline: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphicspipeline
.PHONY : graphicspipeline

# fast build rule for target.
graphicspipeline/fast:
	$(MAKE) -f CMakeFiles/graphicspipeline.dir/build.make CMakeFiles/graphicspipeline.dir/build
.PHONY : graphicspipeline/fast

graphicspipeline.o: graphicspipeline.cpp.o

.PHONY : graphicspipeline.o

# target to build an object file
graphicspipeline.cpp.o:
	$(MAKE) -f CMakeFiles/graphicspipeline.dir/build.make CMakeFiles/graphicspipeline.dir/graphicspipeline.cpp.o
.PHONY : graphicspipeline.cpp.o

graphicspipeline.i: graphicspipeline.cpp.i

.PHONY : graphicspipeline.i

# target to preprocess a source file
graphicspipeline.cpp.i:
	$(MAKE) -f CMakeFiles/graphicspipeline.dir/build.make CMakeFiles/graphicspipeline.dir/graphicspipeline.cpp.i
.PHONY : graphicspipeline.cpp.i

graphicspipeline.s: graphicspipeline.cpp.s

.PHONY : graphicspipeline.s

# target to generate assembly for a file
graphicspipeline.cpp.s:
	$(MAKE) -f CMakeFiles/graphicspipeline.dir/build.make CMakeFiles/graphicspipeline.dir/graphicspipeline.cpp.s
.PHONY : graphicspipeline.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/graphicspipe.dir/build.make CMakeFiles/graphicspipe.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/graphicspipe.dir/build.make CMakeFiles/graphicspipe.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/graphicspipe.dir/build.make CMakeFiles/graphicspipe.dir/main.cpp.s
.PHONY : main.cpp.s

physicspipeline.o: physicspipeline.cpp.o

.PHONY : physicspipeline.o

# target to build an object file
physicspipeline.cpp.o:
	$(MAKE) -f CMakeFiles/physicspipeline.dir/build.make CMakeFiles/physicspipeline.dir/physicspipeline.cpp.o
.PHONY : physicspipeline.cpp.o

physicspipeline.i: physicspipeline.cpp.i

.PHONY : physicspipeline.i

# target to preprocess a source file
physicspipeline.cpp.i:
	$(MAKE) -f CMakeFiles/physicspipeline.dir/build.make CMakeFiles/physicspipeline.dir/physicspipeline.cpp.i
.PHONY : physicspipeline.cpp.i

physicspipeline.s: physicspipeline.cpp.s

.PHONY : physicspipeline.s

# target to generate assembly for a file
physicspipeline.cpp.s:
	$(MAKE) -f CMakeFiles/physicspipeline.dir/build.make CMakeFiles/physicspipeline.dir/physicspipeline.cpp.s
.PHONY : physicspipeline.cpp.s

state.o: state.cpp.o

.PHONY : state.o

# target to build an object file
state.cpp.o:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/state.cpp.o
.PHONY : state.cpp.o

state.i: state.cpp.i

.PHONY : state.i

# target to preprocess a source file
state.cpp.i:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/state.cpp.i
.PHONY : state.cpp.i

state.s: state.cpp.s

.PHONY : state.s

# target to generate assembly for a file
state.cpp.s:
	$(MAKE) -f CMakeFiles/state.dir/build.make CMakeFiles/state.dir/state.cpp.s
.PHONY : state.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... physicspipeline"
	@echo "... state"
	@echo "... graphicspipe"
	@echo "... rebuild_cache"
	@echo "... install/local"
	@echo "... graphicspipeline"
	@echo "... edit_cache"
	@echo "... graphicspipeline.o"
	@echo "... graphicspipeline.i"
	@echo "... graphicspipeline.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... physicspipeline.o"
	@echo "... physicspipeline.i"
	@echo "... physicspipeline.s"
	@echo "... state.o"
	@echo "... state.i"
	@echo "... state.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

